openapi: 3.0.0
info:
  title: Forecast
  version: '1.0'
  description: Set and read forecast for specific city.
  contact:
    name: Jurica Separoic
    url: separovic.dev
    email: jurica.separovic@gmail.com
servers:
  - url: 'http://forecaster.com'
    description: Forecaster
paths:
  '/api/v3/cities/{id}/forecasts':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        description: City id
        required: true
    get:
      summary: Get city forecast
      tags: []
      operationId: get-api-v3-cities-id-forecast
      description: Get forecast for specificy city
      parameters:
        - schema:
            type: string
            format: date
            example: '2020-11-19'
          in: query
          name: date
          description: Get city forecast for specific date
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  $ref: '#/components/schemas/Forecast'
              examples:
                Two day forecast for city:
                  value:
                    - id: 299bee2f-bbf9-41f2-8b32-010482c6c8f5
                      day: '2020-11-19'
                      temperature:
                        celsius: 24
                        fahrenheit: 75.2
                    - id: 123123-bbf9-41f2-8b32-010482c6c8f5
                      day: '2020-12-19'
                      temperature:
                        celsius: 25
                        fahrenheit: 76.2
    post:
      summary: Add city forecast
      operationId: post-api-v3-cities-id-forecast
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateForecastRequest'
            examples:
              Temperature for 19th of November:
                value:
                  date: '2020-11-19'
                  temperature:
                    celsius: 24
                    fahrenheit: 75.2
        description: ''
      description: Add forecast for specific city.
      responses:
        '201':
          description: Forecast created
          headers: {}
          content:
            application/json:
              schema:
                type: object
              examples:
                Creation success:
                  value: {}
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationFailedResponse'
              examples: {}
components:
  schemas:
    CreateForecastRequest:
      description: Add forecast reuquest
      type: object
      properties:
        date:
          type: string
          minLength: 1
        temperature:
          type: object
          properties:
            celsius:
              type: number
            fahrenheit:
              type: number
          required:
            - celsius
            - fahrenheit
      required:
        - date
        - temperature
      x-examples:
        Create forecast for 11th of November:
          date: '2020-11-19'
          temperature:
            celsius: 24
            fahrenheit: 75.2
      title: Add forecast request
    ValidationFailedResponse:
      description: ''
      type: object
      x-examples:
        Invalid input field:
          title: Unprocessable Entity
          type: 'https://httpstatus.es/422'
          status: 422
          detail: Input validation failed.
          validation_failures:
            - id: email
              message: This field is not a valid email address.
              value: h4ck3r@@mail
      properties:
        title:
          type: string
          minLength: 1
          description: Exception title
          enum:
            - Unprocessable Entity
        type:
          type: string
          minLength: 1
          enum:
            - 'https://httpstatus.es/422'
        status:
          type: number
          enum:
            - 422
        detail:
          type: string
          minLength: 1
          enum:
            - Input validation failed.
        validation_failures:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              message:
                type: string
                minLength: 1
              value:
                type: string
              id:
                type: string
            required:
              - message
              - value
      required:
        - title
        - type
        - status
        - detail
        - validation_failures
    Forecast:
      description: ''
      type: object
      x-examples:
        Forecast for 11th of November:
          id: 299bee2f-bbf9-41f2-8b32-010482c6c8f5
          day: '2020-11-19'
          temperature:
            celsius: 24
            fahrenheit: 75.2
      properties:
        id:
          type: string
          minLength: 1
        date:
          type: string
          minLength: 1
        temperature:
          type: object
          required:
            - celsius
            - fahrenheit
          properties:
            celsius:
              type: number
            fahrenheit:
              type: number
      required:
        - id
        - date
        - temperature
  securitySchemes: {}
